In [1]:
import pandas as pd

In [36]:
equal_dex = pd.read_csv("equaldex_equality_index-2024-dec.csv")
equal_dex.head()

  Region ID     Name  EI  EI Legal  EI PO
0        IS  Iceland  93        95   90.0
1        NO   Norway  87        87   87.0
2        ES    Spain  83       100   67.0
3        UY  Uruguay  83        93   73.0
4        DE  Germany  81       100   62.0

In [37]:
ess = pd.read_csv("ESS11e04_1/ESS11e04_1.csv")
ess.head()

C:\Users\Jinal\AppData\Local\Temp\ipykernel_4100\1919858798.py:1: DtypeWarning: Columns (0: cntbrthd, 1: fbrncntc, 2: rinwe) have mixed types. Specify dtype option on import or set low_memory=False.
  ess = pd.read_csv("ESS11e04_1/ESS11e04_1.csv")

,name,essround,edition,proddate,idno,cntry,dweight,pspwght,pweight,anweight,...,rinwe,inwde,jinws,jinwe,inwtm,mode,domain,prob,stratum,psu
0,ESS11e04_1,11,4.1,12.01.2026,50014,AT,1.185115,0.392891,0.330915,0.130013,...,NaN,2023-11-12 15:26:55,2023-11-12 15:21:28,2023-11-12 15:26:55,30.0,1,2.0,0.000579,107,317
1,ESS11e04_1,11,4.1,12.01.2026,50030,AT,0.609898,0.325153,0.330915,0.107598,...,NaN,2023-10-18 10:44:18,2023-10-18 10:42:22,2023-10-18 10:44:18,40.0,1,1.0,0.001124,69,128
2,ESS11e04_1,11,4.1,12.01.2026,50057,AT,1.392330,4.000023,0.330915,1.323666,...,NaN,2023-09-30 14:13:33,2023-09-30 14:08:31,2023-09-30 14:13:33,42.0,1,2.0,0.000493,18,418
3,ESS11e04_1,11,4.1,12.01.2026,50106,AT,0.556061,0.176228,0.330915,0.058316,...,NaN,2023-06-30 15:11:21,2023-06-30 15:08:05,2023-06-30 15:11:21,34.0,1,1.0,0.001233,101,295
4,ESS11e04_1,11,4.1,12.01.2026,50145,AT,0.722795,1.060940,0.330915,0.351080,...,NaN,2023-07-11 11:14:03,2023-07-11 11:10:02,2023-07-11 11:14:03,57.0,1,2.0,0.000949,115,344

In [39]:
ess_cc = pd.read_csv("ess_country_codes.csv")
ess_cc.head()

  Value     Category
0     AL      Albania
1     AT      Austria
2     BE      Belgium
3     BG     Bulgaria
4     CH  Switzerland

In [40]:
ess["cntryname"] = ess["cntry"].apply(lambda x: ess_cc[ess_cc["Value "] == x]["Category "].values[0])

C:\Users\Jinal\AppData\Local\Temp\ipykernel_4100\3915239163.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ess["cntryname"] = ess["cntry"].apply(lambda x: ess_cc[ess_cc["Value "] == x]["Category "].values[0])

In [ ]:
ess["sclmeet_wg"] = ess["sclmeet"] * ess["anweight"]
ess["rlgblg_wg"] = ess["rlgblg"] * ess["anweight"]
ess["rlgdgr_wg"] = ess["rlgdgr"] * ess["anweight"]

In [65]:
df = ess[["cntry", "sclmeet", "rlgblg", "rlgdgr", "sclmeet_wg", "rlgblg_wg", "rlgdgr_wg"]].groupby(by = "cntry", as_index=False).mean()
df.head()

  cntry   sclmeet    rlgblg    rlgdgr  sclmeet_wg  rlgblg_wg  rlgdgr_wg
0    AT  4.922260  1.338573  5.151657    1.656219   0.453005   1.621730
1    BE  5.190088  1.616060  4.376412    3.157097   0.991500   2.936396
2    BG  5.177311  1.281822  4.297901    1.269545   0.320960   1.023402
3    CH  5.222543  1.503613  4.986272    2.845744   0.813192   2.639653
4    CY  4.005839  1.094891  7.064234    0.458248   0.124907   0.771783

In [66]:
df.to_csv("ess_country_level_means.csv")